// ================= 設定區 =================
// 請填入您的 Gemini API Key (從 Google AI Studio 取得)
const GEMINI_API_KEY = 'YOUR_GEMINI_API_KEY_HERE';

// 請填入您的 Discord Webhook 網址
const DISCORD_WEBHOOK_URL = 'YOUR_DISCORD_WEBHOOK_URL_HERE';
// =========================================

function processAllTLDREmails() {
  // 一次處理 3 封，避免超時
  const threads = GmailApp.search('from:TLDR is:unread', 0, 3); 

  if (threads.length === 0) {
    console.log("目前沒有新的 TLDR 信件");
    return;
  }

  for (const thread of threads) {
    const message = thread.getMessages()[0];
    const subject = message.getSubject();
    const body = message.getPlainBody();
    const sender = message.getFrom().toUpperCase(); 

    // 分類邏輯
    let newsletterType = "綜合科技";
    if (sender.includes("TLDR CRYPTO")) newsletterType = "Web3 與區塊鏈";
    else if (sender.includes("TLDR AI")) newsletterType = "人工智慧";
    else if (sender.includes("TLDR DEVOPS")) newsletterType = "DevOps";
    else if (sender.includes("TLDR INFOSEC")) newsletterType = "資安";
    else if (sender.includes("TLDR FINTECH")) newsletterType = "金融科技";
    else if (sender.includes("TLDR FOUNDERS")) newsletterType = "創業";
    else if (sender.includes("TLDR PRODUCT")) newsletterType = "產品";
    else if (sender.includes("TLDR DEV")) newsletterType = "軟體開發";
    else if (sender.includes("TLDR MARKETING")) newsletterType = "行銷";
    else if (sender.includes("TLDR DESIGN")) newsletterType = "設計";
    else if (sender.includes("TLDR DATA")) newsletterType = "資料科學";

    console.log(`處理信件：${subject} (${newsletterType})`);

    // 呼叫 AI 產生 Discord 專用的 Markdown 內容
    const summaryMarkdown = callGeminiAPI(body, newsletterType);
    
    if (summaryMarkdown) {
      // 發送到 Discord
      sendToDiscord(newsletterType, summaryMarkdown);
      
      // 標記已讀
      thread.markRead(); 
      
      // 冷卻時間
      console.log("休息 5 秒...");
      Utilities.sleep(5000); 
    }
  }
}

function callGeminiAPI(emailContent, type) {
  // 使用你測試成功的 2.5 版本
  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`;
  
  const promptText = `
    你是一個 ${type} 領域的快訊機器人。請閱讀以下 TLDR 電子報，並用「繁體中文」寫一份適合發在 Discord 的 Markdown 懶人包。

    【排版要求】
    1. 使用 Emoji 讓版面生動 (如 🚨, ⚡, 💡)。
    2. 使用 **粗體** 標示重點。
    3. 連結請使用 [連結標題](網址) 的格式。
    4. 字數控制在 1000 字以內。
    5. 不要使用 HTML 標籤。
    
    【輸出格式範例】
    **🚨 頭條大事**
    * 這裡寫重點... [查看更多](URL)
    
    **💡 關鍵趨勢**
    * 這裡寫趨勢...

    信件內容：
    ${emailContent}
  `;

  const payload = {
    "contents": [{
      "parts": [{ "text": promptText }]
    }]
  };

  const options = {
    "method": "post",
    "contentType": "application/json",
    "payload": JSON.stringify(payload),
    "muteHttpExceptions": true
  };

  try {
    const response = UrlFetchApp.fetch(url, options);
    const json = JSON.parse(response.getContentText());
    
    if (json.error) {
      console.log("Gemini API Error: " + json.error.message);
      return null;
    }
    return json.candidates[0].content.parts[0].text;

  } catch (e) {
    console.log("Gemini API 呼叫失敗: " + e.toString());
    return null;
  }
}

// 🔥 傳送給 Discord 的函式 (修復 today is not defined)
function sendToDiscord(type, content) {
  // 1. 這裡定義 today，確保不會報錯
  const today = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), "yyyy/MM/dd");

  // Discord 的顏色代碼
  let color = 5814783; // 預設藍色
  if (type.includes("Web3")) color = 15105570; // 橘色 (Web3)
  else if (type.includes("人工智慧")) color = 10181046; // 紫色 (AI)
  else if (type.includes("資安")) color = 15158332; // 紅色 (InfoSec)

  const payload = {
    "embeds": [{
      // 標題加入日期
      "title": `${today} | 📅 最新 ${type} 日報彙整`,
      "description": content,
      "color": color,
      "footer": {
        "text": "Generated by Gemini AI • TLDR Bot"
      },
      "timestamp": new Date().toISOString()
    }]
  };

  const options = {
    "method": "post",
    "contentType": "application/json",
    "payload": JSON.stringify(payload)
  };

  try {
    UrlFetchApp.fetch(DISCORD_WEBHOOK_URL, options);
    console.log(`[${today}] 已發送至 Discord`);
  } catch (e) {
    console.log("Discord 發送失敗: " + e.toString());
  }
}
